
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BYTE COMPRESSED_STRING DICT_HEADER NUMBER ONE REF16 REF32 REF4 REF8 ZERO\nprog : DICT_HEADER op_list\n\nop_list : op_list op\n        | op\n\nop : input\n   | inputs\n   | print\n   | printex\n   | goto\n   | if\n   | ifc\n\ninput : ZERO ZERO ZERO ZERO constant\n      | ZERO ZERO ZERO ONE number\n\ninputs : ZERO ZERO ONE ZERO constant\n       | ZERO ZERO ONE ONE number\n\nprint : ZERO ONE ZERO ZERO constant\n      | ZERO ONE ZERO ONE number\n\nprintex : ZERO ONE ONE ZERO constant\n        | ZERO ONE ONE ONE number\n\ngoto : ONE ZERO ZERO number\n\nif : ONE ZERO ONE ZERO constant number\n   | ONE ZERO ONE ONE number number\n\nifc : ONE ONE ZERO rel_op ZERO operand number\n    | ONE ONE ZERO rel_op ONE operand number\n\noperand : optype NUMBER\n\noptype : ZERO\n       | ONE\n\nconstant : marker4 COMPRESSED_STRING\n\nmarker4 :\n\nstype : ZERO marker2 ZERO\n      | ZERO marker3 ONE\n\nmarker2 :\n\nmarker3 :\n\nbyte_list : byte_list BYTE\n          | BYTE\n\nnumber : marker ref\n\nmarker :\n\nref : ZERO REF4\n    | ONE REF4\n    | ONE REF8\n    | ONE REF16\n    | ONE REF32\n\nrel_op : ZERO ZERO ZERO \n       | ZERO ZERO ONE\n       | ZERO ONE ZERO \n       | ZERO ONE ONE\n       | ONE ZERO ZERO \n       | ONE ZERO ONE\n\neot : ZERO ZERO ZERO ZERO ZERO ONE ONE\n    | ZERO ZERO ZERO ZERO ZERO ZERO ONE ONE\n'
    
_lr_action_items = {'DICT_HEADER':([0,],[2,]),'$end':([1,3,4,5,6,7,8,9,10,11,14,39,41,43,44,45,46,47,48,49,57,60,72,73,74,75,76,77,78,79,81,],[0,-1,-3,-4,-5,-6,-7,-8,-9,-10,-2,-19,-11,-12,-13,-14,-15,-16,-17,-18,-35,-27,-21,-20,-37,-38,-39,-40,-41,-23,-22,]),'ZERO':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,29,31,33,34,35,36,37,39,40,41,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,60,61,62,63,64,65,66,69,71,72,73,74,75,76,77,78,79,80,81,],[12,12,-3,-4,-5,-6,-7,-8,-9,-10,15,18,-2,19,21,23,25,26,28,30,32,35,38,-36,-36,-36,-36,-36,50,51,54,-36,-19,58,-11,-12,-13,-14,-15,-16,-17,-18,62,63,65,68,68,-36,-36,-35,-27,-47,-46,-42,-43,-44,-45,-36,-36,-21,-20,-37,-38,-39,-40,-41,-23,-24,-22,]),'ONE':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,27,29,31,33,35,36,37,39,40,41,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,60,61,62,63,64,65,66,69,71,72,73,74,75,76,77,78,79,80,81,],[13,13,-3,-4,-5,-6,-7,-8,-9,-10,16,17,-2,20,22,24,27,29,31,33,34,37,-36,-36,-36,-36,-36,52,53,-36,-19,59,-11,-12,-13,-14,-15,-16,-17,-18,61,64,66,67,67,-36,-36,-35,-27,-47,-46,-42,-43,-44,-45,-36,-36,-21,-20,-37,-38,-39,-40,-41,-23,-24,-22,]),'COMPRESSED_STRING':([26,28,30,32,38,42,],[-28,-28,-28,-28,-28,60,]),'REF4':([58,59,],[74,75,]),'REF8':([59,],[76,]),'REF16':([59,],[77,]),'REF32':([59,],[78,]),'NUMBER':([67,68,70,],[-26,-25,80,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'op_list':([2,],[3,]),'op':([2,3,],[4,14,]),'input':([2,3,],[5,5,]),'inputs':([2,3,],[6,6,]),'print':([2,3,],[7,7,]),'printex':([2,3,],[8,8,]),'goto':([2,3,],[9,9,]),'if':([2,3,],[10,10,]),'ifc':([2,3,],[11,11,]),'rel_op':([23,],[36,]),'number':([25,27,29,31,33,37,55,56,69,71,],[39,43,45,47,49,55,72,73,79,81,]),'marker':([25,27,29,31,33,37,55,56,69,71,],[40,40,40,40,40,40,40,40,40,40,]),'constant':([26,28,30,32,38,],[41,44,46,48,56,]),'marker4':([26,28,30,32,38,],[42,42,42,42,42,]),'ref':([40,],[57,]),'operand':([53,54,],[69,71,]),'optype':([53,54,],[70,70,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> DICT_HEADER op_list','prog',2,'p_prog','myParser.py',63),
  ('op_list -> op_list op','op_list',2,'p_op_list','myParser.py',70),
  ('op_list -> op','op_list',1,'p_op_list','myParser.py',71),
  ('op -> input','op',1,'p_op','myParser.py',80),
  ('op -> inputs','op',1,'p_op','myParser.py',81),
  ('op -> print','op',1,'p_op','myParser.py',82),
  ('op -> printex','op',1,'p_op','myParser.py',83),
  ('op -> goto','op',1,'p_op','myParser.py',84),
  ('op -> if','op',1,'p_op','myParser.py',85),
  ('op -> ifc','op',1,'p_op','myParser.py',86),
  ('input -> ZERO ZERO ZERO ZERO constant','input',5,'p_input','myParser.py',92),
  ('input -> ZERO ZERO ZERO ONE number','input',5,'p_input','myParser.py',93),
  ('inputs -> ZERO ZERO ONE ZERO constant','inputs',5,'p_inputs','myParser.py',108),
  ('inputs -> ZERO ZERO ONE ONE number','inputs',5,'p_inputs','myParser.py',109),
  ('print -> ZERO ONE ZERO ZERO constant','print',5,'p_print','myParser.py',124),
  ('print -> ZERO ONE ZERO ONE number','print',5,'p_print','myParser.py',125),
  ('printex -> ZERO ONE ONE ZERO constant','printex',5,'p_printex','myParser.py',140),
  ('printex -> ZERO ONE ONE ONE number','printex',5,'p_printex','myParser.py',141),
  ('goto -> ONE ZERO ZERO number','goto',4,'p_goto','myParser.py',156),
  ('if -> ONE ZERO ONE ZERO constant number','if',6,'p_if','myParser.py',165),
  ('if -> ONE ZERO ONE ONE number number','if',6,'p_if','myParser.py',166),
  ('ifc -> ONE ONE ZERO rel_op ZERO operand number','ifc',7,'p_ifc','myParser.py',182),
  ('ifc -> ONE ONE ZERO rel_op ONE operand number','ifc',7,'p_ifc','myParser.py',183),
  ('operand -> optype NUMBER','operand',2,'p_operand','myParser.py',206),
  ('optype -> ZERO','optype',1,'p_optype','myParser.py',212),
  ('optype -> ONE','optype',1,'p_optype','myParser.py',213),
  ('constant -> marker4 COMPRESSED_STRING','constant',2,'p_constant','myParser.py',223),
  ('marker4 -> <empty>','marker4',0,'p_marker4','myParser.py',229),
  ('stype -> ZERO marker2 ZERO','stype',3,'p_stype','myParser.py',235),
  ('stype -> ZERO marker3 ONE','stype',3,'p_stype','myParser.py',236),
  ('marker2 -> <empty>','marker2',0,'p_marker2','myParser.py',242),
  ('marker3 -> <empty>','marker3',0,'p_marker3','myParser.py',248),
  ('byte_list -> byte_list BYTE','byte_list',2,'p_byte_list','myParser.py',254),
  ('byte_list -> BYTE','byte_list',1,'p_byte_list','myParser.py',255),
  ('number -> marker ref','number',2,'p_number','myParser.py',264),
  ('marker -> <empty>','marker',0,'p_marker','myParser.py',270),
  ('ref -> ZERO REF4','ref',2,'p_ref','myParser.py',276),
  ('ref -> ONE REF4','ref',2,'p_ref','myParser.py',277),
  ('ref -> ONE REF8','ref',2,'p_ref','myParser.py',278),
  ('ref -> ONE REF16','ref',2,'p_ref','myParser.py',279),
  ('ref -> ONE REF32','ref',2,'p_ref','myParser.py',280),
  ('rel_op -> ZERO ZERO ZERO','rel_op',3,'p_rel_op','myParser.py',286),
  ('rel_op -> ZERO ZERO ONE','rel_op',3,'p_rel_op','myParser.py',287),
  ('rel_op -> ZERO ONE ZERO','rel_op',3,'p_rel_op','myParser.py',288),
  ('rel_op -> ZERO ONE ONE','rel_op',3,'p_rel_op','myParser.py',289),
  ('rel_op -> ONE ZERO ZERO','rel_op',3,'p_rel_op','myParser.py',290),
  ('rel_op -> ONE ZERO ONE','rel_op',3,'p_rel_op','myParser.py',291),
  ('eot -> ZERO ZERO ZERO ZERO ZERO ONE ONE','eot',7,'p_eot','myParser.py',309),
  ('eot -> ZERO ZERO ZERO ZERO ZERO ZERO ONE ONE','eot',8,'p_eot','myParser.py',310),
]
